[tasks.build]
clear = true
command = "pnpm"
args = ["astro", "build"]

[tasks.clean]
clear = true
command = "pnpm"
args = ["trash", "public/"]

[tasks.dev]
clear = true
command = "pnpm"
args = ["astro", "dev"]

[tasks.publish]
clear = true
dependencies = ["clean", "build"]
command = "pnpm"
args = ["netlify", "deploy", "-p", "-d", "public/", "-s", "tildes.community"]
